# Configurations
title:            TauEst
longtitle:        TauEst
email:            shevshenko.andrey.uzurpastor@gmail.com
description: >
  TauEst - website for testing employees of the organization. The application has a client-server architecture

version:          1.0
gitbook_version:  3.2.3

url:              'https://uzurpastor.github.io'
rss:              RSS


api:              '/assets/api'
styles:           '/assets/styles'
images:           '/assets/images'
scripts:          '/assets/scripts'
# bootstrap: use the remote theme for the site itself
# remote_theme: uzurpastor/tau_est_cli

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji


ssl-key:  config/local-cert/localhost-key.pem
ssl-cert: config/local-cert/localhost.pem